name: Deploy

on:
  push:
    branches:
      - main

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:

      - name: Set up Python 3.7
        uses: actions/setup-python@v3
        with:
          python-version: 3.7
        
      - name: Set up Python 3.7
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install pip
        run: |
          sudo apt install python3-pip
          python -m pip install --upgrade pip setuptools wheel

      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install Python Packages
        run: pip install -r ${{ github.workspace }}/test-requirements.txt

      - name: Run Tox/Pytests
        run: export PYTHONPATH=${{ github.workspace }} && tox